@****************************************************************
@Copyright (C) ,2016 fxk
@File name:	led_on.S
@Aunthor:	fxk       Version: V0.1    Date:2016.12.05
@Description: This is my first JZ2440 assembly code.	  				 	
@Function List:  
@History: 
@<author>  <time>  <version>  <desc>
@
@****************************************************************

.text				 @ compiled code will be in the code segment
.global